### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by HiroIshida** [HiroIshida/SequentialQP.jl#1]
- [ ] simple hessian approximation strategy 
- [ ] give it a try with a large scale model, and compare the computation time with scipy.SLSQP. probably, in the current implementation, scipy must be efficient, 
- [ ] Try not to create the sparse matrix all the time. => creation of sparsematrix seems to be zero-cost 
- [ ] use OSQP's warm starting (by default??)
